name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: docker
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CI_REGISTRY }} -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.CI_REGISTRY }}/myapp:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.CI_REGISTRY }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          IMAGE=${{ secrets.CI_REGISTRY }}/myapp:${{ github.sha }}
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            docker login ${{ secrets.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} &&
            docker pull $IMAGE &&
            docker stop incom || true &&
            docker rm incom || true &&
            docker run -d --restart unless-stopped -p 8000:80 --name incom $IMAGE
          "
